GROUP=io.github.joelromanpr.charts
VERSION_NAME=2.1.0-SNAPSHOT
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
POM_URL=https://github.com/joelromanpr/jetpack-charts
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/joelromanpr/jetpack-charts
POM_SCM_CONNECTION=scm:git:https://github.com/joelromanpr/jetpack-charts.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/joelromanpr/jetpack-charts.git
